### ISSUE TITLE
bili的上传文件无法下载

### ISSUE THREAD

**Issue by StudenGit** [apachecn/CDNDrive#39]
之前一直没问题的，最近一两周出现的问题，上传的时候没问题，但是下载失败：

cdrive download bdex://5787c80246b33*****************
Traceback (most recent call last):
  File "E:\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Programs\Python\Python310\Scripts\cdrive.exe\__main__.py", line 7, in <module>
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 329, in main
    args.func(args)
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 203, in download_handle
    meta_dict = fetch_meta(args.meta)
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 50, in fetch_meta
    meta_dict = json.loads(encoder.decode(full_meta).decode("utf-8"))
  File "E:\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

用的时Windows系统，同时上传的baijia和微博都没问题，可以下载下来

**Comment by StudenGit** [comment]
这个项目是不是已经不再维护了啊

**Comment by StudenGit** [comment]
好像每次的报错信息都不一样
cdrive info bdex://03a11f9d08da416e790c869e8606464058830be5Traceback (most recent call last):
  File "E:\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Programs\Python\Python310\Scripts\cdrive.exe\__main__.py", line 7, in <module>
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 329, in main
    args.func(args)
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 251, in info_handle
    meta_dict = fetch_meta(args.meta)
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 50, in fetch_meta
    meta_dict = json.loads(encoder.decode(full_meta).decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 80: invalid start byte

**Comment by StudenGit** [comment]
cdrive download bdex://c4a21cdbbeca1c70***************
Traceback (most recent call last):
  File "E:\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Programs\Python\Python310\Scripts\cdrive.exe\__main__.py", line 7, in <module>
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 329, in main
    args.func(args)
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 203, in download_handle
    meta_dict = fetch_meta(args.meta)
  File "E:\Programs\Python\Python310\lib\site-packages\CDNDrive\__main__.py", line 50, in fetch_meta
    meta_dict = json.loads(encoder.decode(full_meta).decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte

**Comment by RELemon** [comment]
我也遇到了同样的问题，下载网上的bdex是可以的

**Comment by HIbian** [comment]
上传60MB文件实验，发现上传时meta文件和下回来的meta文件不一样，b站把上传的meta文件夹了一截。

* 上传的meta
https://github.com/apachecn/CDNDrive/blob/861e16fd510a929a22514fcef2c1b14a38f29fc9/CDNDrive/__main__.py#L157-L158
* 下载的meta
https://github.com/apachecn/CDNDrive/blob/861e16fd510a929a22514fcef2c1b14a38f29fc9/CDNDrive/__main__.py#L45-L48
![image](https://user-images.githubusercontent.com/31313237/198524194-68462c92-24c5-4d0b-82ae-24a2473c52b7.png)
![image](https://user-images.githubusercontent.com/31313237/198524732-4d4e5b01-d31e-4723-88be-ece7b2427086.png)

**Comment by lemonchu** [comment]
只有meta被截断，还是载有文件内容的图片也被截断了？
