### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by Janet-Baker** [apachecn/CDNDrive#9]
```
[root@linode bilibili_椎名菜羽-ShiinaNanoha_22347054]# cdrive upload ali 【B限】钢琴弾唱♪_20200830200230754.flv
[2020-08-30 23:49:38] 上传: 【B限】钢琴弾唱♪_20200830200230754.flv (1.70 GB)
Traceback (most recent call last):
  File "/usr/local/bin/cdrive", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/CDNDrive/__main__.py", line 321, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/CDNDrive/__main__.py", line 120, in upload_handle
    history = read_history(args.site)
  File "/usr/local/lib/python3.6/site-packages/CDNDrive/util.py", line 64, in read_history
    history = json.loads(f.read())
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[root@linode bilibili_椎名菜羽-ShiinaNanoha_22347054]#
```

**Comment by Janet-Baker** [comment]
怀疑和我手动清空了/tmp/cdrive_history.json有关，只清空了内容，留下了一个空文件。
希望能改进一下异常处理机制，。
